export interface CareerQuestion {
  id: number;
  es: string;
  en: string;
  fr: string;
  ar: string;
  category: "tech" | "health" | "business" | "hospitality" | "creative";
  points: number;
}

export const CAREER_CATEGORIES = {
  tech: {
    es: "Informática, Redes y Programación",
    en: "IT, Networks & Programming",
    fr: "Informatique, Réseaux & Programmation",
    ar: "المعلوماتية والبرمجة والشبكات",
    recommendation: {
      title: "FP Superior en DAW (Desarrollo de Aplicaciones Web) / Ingeniería Informática",
      es: "Tu perfil es ideal para la tecnología. Te recomendamos cursar un Grado Superior en Desarrollo (DAW) o una Ingeniería en España. Tienen un 95% de inserción laboral inmediata.",
      ar: "ملفك مثالي للتكنولوجيا. نوصيك بالتسجيل في DAW أو هندسة البرمجيات في إسبانيا مع معدل توظيف 95٪.",
      fr: "Votre profil est idéal pour la technologie. Nous conseillons un diplôme DAW ou ingénierie informatique en Espagne. Taux d'insertion de 95%.",
      en: "Your profile is best for technology. We highly recommend a Higher Degree in Web App Development (DAW) or Computer Science in Spain."
    }
  },
  health: {
    es: "Enfermería, Odontología y Ramo Sanitario",
    en: "Nursing, Healthcare & Oral Health",
    fr: "Soins Auxiliaires, Odontologie & Santé",
    ar: "التمريض والرعاية والقطاع الصحي",
    recommendation: {
      title: "TCAE (Auxiliar de Enfermería) / Grado en Enfermería o Fisioterapia",
      es: "Tienes una fuerte vocación de servicio. Enfermería y TCAE tienen una demanda insaciable y bolsas de empleo públicas garantizadas en toda España.",
      ar: "لديك شغف كبير لمساعدة الآخرين. التمريض ومساعد التمريض لديهما طلب دائم ومضمون في جميع أنحاء إسبانيا.",
      fr: "Vocation humaine évidente. Les soins auxiliaires et infirmiers ont une demande record et continue en Espagne.",
      en: "Strong human vocation. General Nursing or Certified Nursing Auxiliary (TCAE) has a guaranteed career path in Spain."
    }
  },
  business: {
    es: "Administración, Marketing y Gestión de Negocios",
    en: "Administration, Marketing & Commerce",
    fr: "Administration, Marketing & Ventes",
    ar: "الإدارة والتسويق وتسيير المقاولات",
    recommendation: {
      title: "Grado Superior en Gestión Administrativa / Grado en ADE o Comercio",
      es: "Eres organizado/a y estratega. Un Grado en ADE o FP en Administración y Finanzas te abrirá puestos estables en corporaciones multinacionales.",
      ar: "أنت منظم ومخطط رائع. الإدارة والمالية والمبيعات ستفتح لك مناصب مهمة ومستقرة في الشركات الكبرى.",
      fr: "Excellent sens de l'organisation. L'administration d'entreprises (ADE) ou le commerce international vous ouvriront de grands débouchés.",
      en: "Highly organized profile. Business Administration (ADE) or Trade/Logistics is highly valued by Spanish and multinational corporations."
    }
  },
  hospitality: {
    es: "Turismo, Relaciones Públicas y Hostelería",
    en: "Tourism, Public Relations & Hospitality",
    fr: "Tourisme, Événementiel & Restauration",
    ar: "السياحة والترجمة والإرشاد الفندقي",
    recommendation: {
      title: "Grado Superior en Alojamientos Turísticos / Dirección de Hostelería",
      es: "España es potencia mundial en turismo. Tus idiomas nativos más un Grado Superior en Guía o Alojamientos Turísticos te convertirán en un perfil estelar.",
      ar: "إسبانيا هي قوة عالمية في السياحة. إتقانك للغات الأجنبية بالإضافة للتكوين الفندقي سيجعلك مرشحاً رائعاً في الوكالات و الفنادق.",
      fr: "L'Espagne est le leader mondial du tourisme. Vos langues combinées à la gestion hôtelière feront de vous un profil de premier plan.",
      en: "Spain is a global tourism powerhouse. Your native languages combined with Hotel Management or Tour Guiding will make you a prime candidate."
    }
  },
  creative: {
    es: "Diseño Gráfico, Bellas Artes y Creación Visual",
    en: "Graphic Design, Arts & Graphic Media",
    fr: "Design Graphique, Création Digitale & Beaux-Arts",
    ar: "التصميم الجرافيكي والفنون والإبداع البصري",
    recommendation: {
      title: "Grado Superior en Diseño Gráfico / Grado Universitario de Creación Visual",
      es: "Tienes un talento creativo excepcional. El Grado Superior de Diseño Gráfico o Web te permitirá trabajar en agencias de publicidad o como freelance.",
      ar: "لديك موهبة إبداعية استثنائية. التصميم الجرافيكي وتصميم المواقع سيجعلك مستعداً للعمل المستقل أو في وكالات الإعلان الإسبانية.",
      fr: "Talent créatif manifeste. Le design graphique et l'UX/UI conviennent à merveille pour le marché des agences digitales en Espagne.",
      en: "Exceptional creative skill. Graphic and digital media design is booming in Spanish advertising, web agency, and freelance sectors."
    }
  }
};

export const HUNDRED_QUESTIONS: CareerQuestion[] = [
  // SECTION 1: TECH (1 - 20)
  { id: 1, category: "tech", points: 5, es: "¿Te atrae resolver acertijo lógicos o rompecabezas complejos?", en: "Do you enjoy resolving logical riddles or complex puzzles?", fr: "Aimez-vous résoudre des énigmes logiques ou des puzzles complexes ?", ar: "هل تستمتع بحل الألغاز المنطقية أو المشاكل المعقدة؟" },
  { id: 2, category: "tech", points: 5, es: "¿Te gustaría construir tus propias aplicaciones móviles o páginas web?", en: "Would you like to build your own mobile applications or websites?", fr: "Aimeriez-vous créer vos propres applications mobiles ou sites web ?", ar: "هل ترغب في بناء تطبيقاتك المحمولة أو مواقعك الإلكترونية الخاصة؟" },
  { id: 3, category: "tech", points: 5, es: "¿Pasas tiempo libre experimentando o investigando con software y tecnología?", en: "Do you explore software, computers, or tech products during spare time?", fr: "Passez-vous du temps libre à explorer de nouveaux logiciels ou technologiques ?", ar: "هل تفضل قضاء وقت فراغك في تصفح وبحث البرمجيات والتقنيات الحديثة؟" },
  { id: 4, category: "tech", points: 5, es: "¿Te interesa saber cómo las redes inalámbricas y el internet funcionan de fondo?", en: "Are you interested in knowing how wireless networks and internet protocols work?", fr: "Êtes-vous curieux de savoir comment fonctionnent les réseaux Wi-Fi et Internet ?", ar: "هل يثير اهتمامك معرفة كيف تسير شبكات الاتصالات والإنترنت في الخلفية؟" },
  { id: 5, category: "tech", points: 5, es: "¿Te agrada automatizar tareas cotidianas repetitivas usando herramientas digitales?", en: "Do you like automating repetitive everyday tasks with digital tools?", fr: "Aimez-vous automatiser des tâches quotidiennes répétitives grâce au numérique ?", ar: "هل يعجبك أتمتة المهام اليومية المتكررة بمساعدة الأدوات الرقمية؟" },
  { id: 6, category: "tech", points: 5, es: "¿Tienes curiosidad por aprender lenguajes de codificación como Python o JavaScript?", en: "Are you curious about learning coding languages like Python or JavaScript?", fr: "Êtes-vous curieux d'apprendre des langages de programmation comme Python ou JS ?", ar: "هل تملك فضولاً لتعلم لغات البرمجة والترميز مثل بايثون أو جافا سكريبت؟" },
  { id: 7, category: "tech", points: 5, es: "¿Te gusta analizar datos concretos y encontrar patrones estadísticos ocultos?", en: "Do you like analyzing concrete data graphs and finding statistical patterns?", fr: "Aimez-vous analyser des données chiffrées et trouver des tendances statistiques ?", ar: "هل تميل إلى تحليل البيانات الرقمية واستخراج الأنماط والإحصاءات؟" },
  { id: 8, category: "tech", points: 5, es: "¿Te gustaría desarrollar herramientas de seguridad inteligente contra piratas?", en: "Would you like to build cybersecurity defenses to protect user databases?", fr: "Aimeriez-vous concevoir des systèmes de sécurité pour déjouer les hackers ?", ar: "هل تود العمل على بناء أنظمة دفاعية لحماية قواعد البيانات وتجنب الاختراق؟" },
  { id: 9, category: "tech", points: 5, es: "¿Te interesan los servidores en la nube y el alojamiento de grandes infraestructuras?", en: "Are you interested in cloud computing systems and hosting server designs?", fr: "Les serveurs cloud et les architectures réseau à grande échelle vous intriguent-ils ?", ar: "هل تجذبك هندسة الحوسبة السحابية وكيفية تشغيل الخوادم العملاقة؟" },
  { id: 10, category: "tech", points: 5, es: "¿Prefieres trabajar frente a un ordenador resolviendo bugs técnicos individuales?", en: "Do you prefer studying bugs and technical computer issues independently?", fr: "Préférez-vous travailler seul devant un écran pour debugguer des terminaux ?", ar: "هل تفضل العمل منفرداً خلف شاشتك لحل المشاكل التقنية وتصحيح الأخطاء؟" },
  { id: 11, category: "tech", points: 5, es: "¿Te imaginas diseñando algoritmos de inteligencia artificial para predecir cosas?", en: "Can you imagine designing smart AI-driven models to predict future trends?", fr: "Vous voyez-vous configurer des algorithmes d'IA pour automatiser le futur ?", ar: "هل تتخيل نفسك مصمماً لخوارزميات الذكاء الاصطناعي لتوقع سلوكيات معينة؟" },
  { id: 12, category: "tech", points: 5, es: "¿Disfrutas desmontando aparatos electrónicos para ver cómo están interconectados?", en: "Do you enjoy opening electronics to see how physical boards are wired?", fr: "Prenez-vous plaisir à démonter des appareils électroniques pour examiner les puces ?", ar: "هل يمتعك تفكيك الأجهزة الإلكترونية لمشاهدة كيفية تواصل مكوناتها وتجميعها؟" },
  { id: 13, category: "tech", points: 5, es: "¿Prefieres soluciones estructuradas y lógicas en lugar de decisiones ambiguas?", en: "Do you favor structured, logical answers over creative visual ambiguity?", fr: "Préférez-vous les solutions rigoureuses et logiques aux compromis créatifs ?", ar: "هل تنحاز دائماً إلى الحلول الهندسية المنطقية وتكره التشتت العشوائي؟" },
  { id: 14, category: "tech", points: 5, es: "¿Te fascina el mundo del blockchain, las bases de datos y la criptografía moderna?", en: "Are you fascinated by crypto ledger techniques and data storage schemes?", fr: "Le fonctionnement de la blockchain et des serveurs distribués vous captive-t-il ?", ar: "هل يسحرك غوص تقنيات البلوك تشين، وتوزيع البيانات الضخمة الآمن؟" },
  { id: 15, category: "tech", points: 5, es: "¿Te mantienes informado/a de las innovaciones tecnológicas globales semanales?", en: "Do you keep up with international technological news regularly?", fr: "Suivez-vous activement l'actualité des innovations high-tech ?", ar: "هل تتابع بحماس وجدية آخر التطورات والأخبار التقنية العالمية أسبوعياً؟" },
  { id: 16, category: "tech", points: 5, es: "¿Disfrutas configurando routers, adaptadores de red y sistemas inalámbricos?", en: "Do you like setting up routers, switches, and local network wiring?", fr: "Aimez-vous configurer des routeurs locaux ou optimiser des réseaux Wi-Fi ?", ar: "هل ترتاح لتثبيت وإعداد أجهزة الواي فاي وتوزيع طاقة الشبكات السلكية؟" },
  { id: 17, category: "tech", points: 5, es: "¿Consideras que las matemáticas y los flujos binarios son hermosos?", en: "Do you think mathematics and logic-flow structures are beautiful?", fr: "Considérez-vous que les mathématiques et la logique sont élégantes ?", ar: "هل ترى أن هناك جمالاً خاصاً في الرياضيات والمعادلات الثنائية؟" },
  { id: 18, category: "tech", points: 5, es: "¿Te gustaría simular entornos gráficos virtuales en motores de videojuegos?", en: "Would you like to write interactive engines to compile 3D game models?", fr: "Aimeriez-vous programmer des mondes virtuels sous Unreal Engine ou Unity ?", ar: "هل تحلم بتصميم وبرمجة محركات الألعاب أو المحاكاة الثلاثية الأبعاد؟" },
  { id: 19, category: "tech", points: 5, es: "¿Prefieres aprender sistemas lógicos abstractos antes que memorizar leyes?", en: "Do you prefer figuring out logical frameworks over memorizing written laws?", fr: "Préférez-vous l'apprentissage par la logique de codage à la mémorisation littéraire ?", ar: "هل تفضل استيعاب المفاهيم التقنية المترابطة على حفظ النصوص والقوانين عن ظهر قلب؟" },
  { id: 20, category: "tech", points: 5, es: "¿Eres paciente para pasar horas buscando una simple coma de error en un script?", en: "Are you patient enough to spend hours spotting a missing comma in raw text?", fr: "Êtes-vous assez patient pour chercher un point-virgule manquant pendant des heures ?", ar: "هل تملك الصبر والجلد للبحث في صفوف الأكواد عن خطأ بسيط لساعات؟" },

  // SECTION 2: HEALTH (21 - 40)
  { id: 21, category: "health", points: 5, es: "¿Te sientes realizado/a cuando alivias el sufrimiento físico de otra persona?", en: "Do you feel fulfilled when you assist in comforting a person's physical pain?", fr: "Vous sentez-vous utile lorsque vous soulagez la douleur physique de quelqu'un ?", ar: "هل تشعر بالراحة العاطفية عندما تسهم في تخفيف معاناة مريض أو شخص متألم؟" },
  { id: 22, category: "health", points: 5, es: "¿Sueles reaccionar con calma y cabeza fría ante situaciones de herida física?", en: "Do you act calmly and logically when faced with accidents or minor wounds?", fr: "Gardez-vous votre sang-froid devant une blessure ou du sang ?", ar: "هل تحافظ على هدوئك وتصرفك السليم عند رؤية الحوادث والجروح؟" },
  { id: 23, category: "health", points: 5, es: "¿Te intriga la biología humana y el funcionamiento microscópico de las células?", en: "Does human biology, medicine, or cell activity fascinate you?", fr: "La biologie humaine et le fonctionnement d'organes microscopiques vous intriguent-ils ?", ar: "هل تبهرك علوم الأحياء وتفاصيل كيفية عمل خلايا الجسم البشري الهندسية؟" },
  { id: 24, category: "health", points: 5, es: "¿Te gustaría trabajar en una clínica, hospital o laboratorio farmacéutico?", en: "Would you like of working inside hospitals, dental departments, or science labs?", fr: "Aimeriez-vous travailler dans une clinique ou un environnement hospitalier ?", ar: "هل تفضل مستقبلاً بيئيًا نظيفًا مثل العمل بمستشفى أو عيادة أو مختبر أبحاث؟" },
  { id: 25, category: "health", points: 5, es: "¿Tienes mucha empatía para escuchar pacientemente a personas de edad avanzada o enfermas?", en: "Do you possess empathy to listen to vulnerable, sick, or elderly people?", fr: "Possédez-vous l'empathie nécessaire pour écouter longuement les aînés ou malades ?", ar: "هل تملك الصبر والرحمة الكافيين للإنصات لكبار السن ومرافقتهم؟" },
  { id: 26, category: "health", points: 5, es: "¿Te gustaría conocer las dosis químicas correctas de medicamentos y sus efectos?", en: "Would you like to study chemical drug reactions, dosages, and user safety?", fr: "Aimeriez-vous apprendre les posologies correctes des médicaments et leurs effets ?", ar: "هل يثيرك علم الأدوية ومقادير تركيباتها وتأثيراتها الكيميائية على الصحة؟" },
  { id: 27, category: "health", points: 5, es: "¿Disfrutas enseñando a otros buenos hábitos de alimentación e higiene médica?", en: "Do you enjoy instilling healthy eating programs or sports hygiene guides?", fr: "Aimez-vous sensibiliser votre entourage à la nutrition et la prévention médicale ?", ar: "هل تفضل نشر الوعي والتربية الصحية والعناية باللياقة والجسد؟" },
  { id: 28, category: "health", points: 5, es: "¿Te atrae la idea de esterilizar y organizar instrumental quirúrgico y médico?", en: "Are you interested in managing and sterilizing medical surgery gear?", fr: "Seriez-vous intéressé par l'organisation et la stérilisation de matériel médical ?", ar: "هل تنظم مستلزماتك بدقة وهل تود إدارة غرف التجهيز والتعقيم السريرية؟" },
  { id: 29, category: "health", points: 5, es: "¿Te interesa aprender cómo los masajes terapéuticos rehabilitan los músculos?", en: "Does physiotherapy, rehabilitation, and muscular therapy appeal to you?", fr: "La kinésithérapie, la rééducation physique et les massages vous intéressent-ils ?", ar: "هل تجد متعة وتفضيلاً في تمارين العلاج الطبيعي وتدليك العضلات المصابة؟" },
  { id: 30, category: "health", points: 5, es: "¿Eres capaz de mantener rutinas higiénicas muy estrictas sin cansarte?", en: "Are you able to respect strict hygiene rules and sanitization cycles daily?", fr: "Pouvez-vous appliquer scrupuleusement des règles sanitaires de désinfection ?", ar: "هل يمكنك تطبيق تدابير النظافة والتعقيم الأكثر صرامة دون إهمال؟" },
  { id: 31, category: "health", points: 5, es: "¿Te gustaría especializarte en primeros auxilios y salvar vidas en apuros?", en: "Would you like to master emergency first-aid and help cardiac victims?", fr: "Aimeriez-vous piloter les premiers secours et gérer l'assistance urgente ?", ar: "هل ترغب في أن تكون الشخص المبادر دائماً بتقديم الإسعافات الأولية لحياة الآخرين؟" },
  { id: 32, category: "health", points: 5, es: "¿Te interesaría estudiar el aparato bucodental y asistir en cirugías de dientes?", en: "Would you like to learn dental health, hygiene, or clinical assistance?", fr: "Êtes-vous attiré par l'assistance en cabinet dentaire ou orthodontie ?", ar: "هل تود معرفة أسرار صحة الأسنان ومرافقة أطباء جراحة الفم؟" },
  { id: 33, category: "health", points: 5, es: "¿Eres meticuloso/a anotando detalles sobre históricos clínicos y constantes vitales?", en: "Are you meticulous when noting clinical symptoms and heart rates?", fr: "Être méticuleux lors de la prise de tension et la tenue de dossier ?", ar: "هل تجد في نفسك مهارة تسجيل ومراقبة مؤشرات ضغط الدم والنبض القياسية؟" },
  { id: 34, category: "health", points: 5, es: "¿Te ves fuerte para tolerar jornadas intensas de trabajo físico de pie?", en: "Do you have the physical stamina to work on your feet during busy shifts?", fr: "Vous sentez-vous fort pour assumer de longues gardes debouts ?", ar: "هل تمتلك اللياقة لتمضية ساعات عمل طويلة في الوقوف ومساعدة الحالات؟" },
  { id: 35, category: "health", points: 5, es: "¿Te gustaría comprender de cerca los virus, anticuerpos y vacunas de defensa?", en: "Would you like to closely investigate viruses, antigens, and vaccine roles?", fr: "Désirez-vous comprendre la virologie et les défenses de vaccination ?", ar: "هل تود التبحر في دراسة مسببات الأمراض كالفيروسات وآليات عمل المناعة الذاتية؟" },
  { id: 36, category: "health", points: 5, es: "¿Consideras la empatía y compasión humana tu mayor rasgo de personalidad?", en: "Is humanitarian empathy and care your absolute greatest strength?", fr: "Considérez-vous le soin d’autrui comme votre trait dominant ?", ar: "هل تعتقد أن اللطف والقدرة على مواساة القلوب الكسيرة هي أسمى سماتك؟" },
  { id: 37, category: "health", points: 5, es: "¿Te llama la atención la psicología clínica y el acompañamiento mental?", en: "Are you interested in medical psychology and mental wellness support?", fr: "L'accompagnement psychologique ou l'aide thérapeutique vous attire-t-il ?", ar: "هل لديك رغبة عميقة بالتعرف على علم النفس التنموي والمساندة النفسية؟" },
  { id: 38, category: "health", points: 5, es: "¿Soportarías ver sangre o fluidos de laboratorio sin asco ni incomodidad?", en: "Can you inspect blood samples without feeling uncomfortable?", fr: "Rédiger des dosages sanguins sans gêne ni recul de sensibilité ?", ar: "هل يمكنك التعامل مع عينات الدم داخل المختبرات دون تردد أو انزعاج؟" },
  { id: 39, category: "health", points: 5, es: "¿Te gustaría colaborar en la rehabilitación motora de niños o deportistas?", en: "Would you love helping coordinate motor rehabilitation for disabled kids?", fr: "Trouveriez-vous enrichissant d'aider des enfants à réhabiliter leur motricité ?", ar: "هل تحب مرافقة مساعي علاج وتأهيل الأطفال أو الرياضيين الحركي؟" },
  { id: 40, category: "health", points: 5, es: "¿Te gustaría trabajar en el sector de la medicina preventiva y dietética?", en: "Do you wish to study dietitian careers or food counseling lines?", fr: "Le domaine de la diététique et des régimes adaptés de santé vous plaît-il ?", ar: "هل تجد رغبتك في أن تكون أخصائي تغذية تنظم جداول طعام صحي للناس؟" },

  // SECTION 3: BUSINESS (41 - 60)
  { id: 41, category: "business", points: 5, es: "¿Disfrutas planificando presupuestos, finanzas personales u hojas contables?", en: "Do you enjoy planning budgets, recording expenses, and spreadsheets?", fr: "Prenez-vous plaisir à tenir des budgets ou manier des tableurs Excel ?", ar: "هل تستمتع بجدولة ميزان مصاريفك الشخصية أو بناء ملفات الإكسل المالية؟" },
  { id: 42, category: "business", points: 5, es: "¿Te ves liderando y motivando a un equipo para alcanzar metas concretas?", en: "Can you see yourself leading, motivating, or coaching a work team?", fr: "Vous imaginez-vous manager une équipe de vente pour atteindre des objectifs ?", ar: "هل ترى في نفسك صفات قائد مبادر قادر على توجيه وتحفيز طاقم العمل؟" },
  { id: 43, category: "business", points: 5, es: "¿Te apasiona la idea de crear, lanzar y hacer crecer tu propio negocio?", en: "Are you passionate about launching and growing your own private startup?", fr: "Le projet de lancer une marque et d’entreprendre vous passionne-t-il ?", ar: "هل تستهويك إلى حد كبير فكرة المخاطرة وبدء مشروعك التجاري الخاص؟" },
  { id: 44, category: "business", points: 5, es: "¿Te gusta analizar por qué cierta publicidad en redes sociales nos convence?", en: "Do you analyze why social media ads make you want to buy things?", fr: "Décryptez-vous les mécanismes publicitaires derrière nos décisions d'achat ?", ar: "هل تتأمل دائماً في الأسباب الذكية التي جعلت إعلاناً ما على السوشيال ميديا يحقق مبيعات؟" },
  { id: 45, category: "business", points: 5, es: "¿Eres persuasivo/a comunicándote y defendiendo tus puntos con firmeza?", en: "Are you persuasive when negotiating and presenting key proposals?", fr: "Êtes-vous négociateur et convaincant lors de présentations ?", ar: "هل تمتاز بطريقة إقناع ممتازة ونقاشات ترتكز على براهين واضحة؟" },
  { id: 46, category: "business", points: 5, es: "¿Te gustaría aprender cómo gestionar la contabilidad fiscal de pymes?", en: "Do you want to learn fiscal accounting for small and medium companies?", fr: "La comptabilité fiscale des PME et l'optimisation des revenus vous plaisent ?", ar: "هل تود سبر أغراض الضرائب والحسابات وتوفير نفقات الشركات الإسبانية؟" },
  { id: 47, category: "business", points: 5, es: "¿Te interesan las inversiones, la bolsa y la gestión patrimonial?", en: "Are you interested in stocks, personal investments, and property assets?", fr: "Les marchés de la bourse, de l'immobilier et de la gestion de fonds vous tentent ?", ar: "هل تقع في نطاق فضولك أحوال البورصة، والأسهم، والاستثمار المالي الذكي؟" },
  { id: 48, category: "business", points: 5, es: "¿Te consideras una persona altamente organizada y orientada a los detalles?", en: "Do you describe yourself as highly organized and detail-oriented?", fr: "Êtes-vous une personne rigoureuse, ordonnée et soucieuse de la clarté ?", ar: "هل تجد من بين طباعك الكفاءة العالية في تنظيم المواعيد وجرد البيانات الدقيقة؟" },
  { id: 49, category: "business", points: 5, es: "¿Te resultaría emocionante negociar contratos comerciales con proveedores?", en: "Would you find negotiating contracts with wholesale suppliers exciting?", fr: "Négocier des clauses de contrats avec des fournisseurs vous plairait-il ?", ar: "هل تحب التفاوض على صفقات مع الموردين الكبار لخفض أسعار السلع؟" },
  { id: 50, category: "business", points: 5, es: "¿Te gustaría comprender los sistemas globales de exportación e importación?", en: "Would you like to study customs laws and international trade logistics?", fr: "Aimeriez-vous comprendre le commerce mondial, le transport et les douanes ?", ar: "هل تحب دراسة قوانين الشحن الجمركي الدولي والتصدير عبر دول العالم؟" },
  { id: 51, category: "business", points: 5, es: "¿Te ves trabajando en una gran oficina gestionando nóminas y contratos?", en: "Do you picture yourself managing wages, payrolls, or legal contracts?", fr: "Vous voyez-vous dans un bureau à rédiger des fiches de paie et contrats ?", ar: "هل تتخيل نفسك موظف موارد بشرية تحرر عقود الرواتب للعمال؟" },
  { id: 52, category: "business", points: 5, es: "¿Disfrutas diseñando logotipos, planes de visibilidad o campañas de marca?", en: "Do you enjoy drafting brand logos, marketing plans, or media campaigns?", fr: "Créer des logos, flyers ou piloter des plans marketing vous plaît ?", ar: "هل تميل إلى تخطيط استراتيجيات بناء الهوية البصرية وزيادة المبيعات للمنتج؟" },
  { id: 53, category: "business", points: 5, es: "¿Prefieres metas de rendimiento claras basadas en comisiones y KPI?", en: "Do you prefer clear job metrics based on sales performance and bonus?", fr: "Préférez-vous être rémunéré sur vos résultats réels et commissions ?", ar: "هل تحب تحديات العمل المستند إلى عمولات مالية ونسب أداء تصاعدية؟" },
  { id: 54, category: "business", points: 5, es: "¿Te atrae la idea de organizar el almacén y el inventario de una gran tienda?", en: "Would you like managing stock counts and warehouse layouts for retail?", fr: "Êtes-vous ordonné pour gérer les inventaires d'un grand entrepôt ?", ar: "هل تحب تنظيم فضاء المبيعات وسلاسل الإمداد ومراقبة النقص في المستودع؟" },
  { id: 55, category: "business", points: 5, es: "¿Consideras útiles las leyes civiles y mercantiles para proteger un negocio?", en: "Are commercial and civil laws useful tools to shield a company?", fr: "Le droit des affaires est-il pour vous un bouclier juridique important ?", ar: "هل تعتبر أن القوانين التجارية والمدنية تهمك لدراستها وممارستها تجارياً؟" },
  { id: 56, category: "business", points: 5, es: "¿Te gustaría dominar hojas de cálculo, diagramas de flujo y bases de datos?", en: "Do you want to master databases, diagrams, and advanced spreadsheets?", fr: "Aimeriez-vous maîtriser à 100% Excel et l'affichage analytique ?", ar: "هل تريد احتراف جمع إحصاءات السوق وبناء المبيعات والتوقعات الرقمية؟" },
  { id: 57, category: "business", points: 5, es: "¿Te gusta atender y resolver de forma cortés las peticiones de clientes descorteses?", en: "Do you like politely pacifying and helping angry or impolite customers?", fr: "Sauriez-vous répondre calmement aux demandes clients de personnes en colère ?", ar: "هل تملك مهارات امتصاص غضب الزبائن الحاد وتحويلهم لعملاء أوفياء؟" },
  { id: 58, category: "business", points: 5, es: "¿Te intriga cómo las tiendas online optimizan sus compras y pasarelas?", en: "Does e-commerce, shopping carts, and transaction funnels intrigue you?", fr: "Les tunnels d'achat et le e-commerce attisent-ils votre curiosité ?", ar: "هل يثيرك سحر المتاجر الإلكترونية وكيفية إقناع المتسوقين بإكمال الطلب؟" },
  { id: 59, category: "business", points: 5, es: "¿Consideras que tienes gran facilidad para las relaciones interpersonales?", en: "Do you feel you have solid social traits to establish business bonds?", fr: "Pensez-vous posséder une grande aisance relationnelle professionnelle ?", ar: "هل تشعر بامتلاكك كاريزما ممتازة لبناء علاقات مهنية واستقطاب المستثمرين؟" },
  { id: 60, category: "business", points: 5, es: "¿Te motiva la gestión del talento, la formación de equipos y el coaching?", en: "Are you motivated by recruiting talents, running workshops, and coaching?", fr: "Recruter, animer et faire progresser une équipe humaine vous motive ?", ar: "هل يحفزك تدريب الفرق البشرية لرفع كفاءتهم وإنتاجيتهم في العمل الجماعي؟" },

  // SECTION 4: HOSPITALITY (61 - 80)
  { id: 61, category: "hospitality", points: 5, es: "¿Te entusiasma viajar, conocer nuevas ciudades y guiar a otras personas?", en: "Do you love traveling, exploring new towns, and guiding visitors?", fr: "Aimez-vous voyager, explorer des villes et guider des groupes ?", ar: "هل تشعر بالشغف بالسفر والتعرف على تاريخ المدن العتيقة وإرشاد الزوار؟" },
  { id: 62, category: "hospitality", points: 5, es: "¿Dominas o te gustaría aplicar múltiples idiomas extranjeros en tu día a día?", en: "Do you speak or want to practice foreign languages in daily work duties?", fr: "Maîtrisez-vous ou voulez-vous pratiquer plusieurs langues au travail ?", ar: "هل تتقن أو تتوق لممارسة عدة لغات عالمية في حواراتك اليومية الحية؟" },
  { id: 63, category: "hospitality", points: 5, es: "¿Te interesan la historia, la cultura y las anécdotas de los monumentos?", en: "Are you interested in historical landmarks, heritage, and monument stories?", fr: "Intéressé par l'histoire locale, le patrimoine et les musées ?", ar: "هل تعشق السير في معالم التاريخ الأثرية ومشاركة قصص وأسرار المآثر التاريخية؟" },
  { id: 64, category: "hospitality", points: 5, es: "¿Te gusta el ambiente multicultural de hoteles, aeropuertos o albergues?", en: "Do you enjoy the dynamic, diverse atmosphere of hotels or transit hubs?", fr: "L'ambiance multiculturelle des gares, aéroports et grands hôtels vous plaît ?", ar: "هل يسعدك مناخ الترحيب المتعدد الثقافات داخل الفنادق والمطارات الدولية؟" },
  { id: 65, category: "hospitality", points: 5, es: "¿Disfrutas recomendando a tus conocidos restaurantes, museos o planes?", en: "Do you like advising friends on outstanding restaurants, galleries, or sights?", fr: "Aimez-vous recommander de bonnes adresses, plats and excursions ?", ar: "هل يحلو لك دائماً ترشيح أفضل المطاعم والمقاهي العتيقة لأصدقائك؟" },
  { id: 66, category: "hospitality", points: 5, es: "¿Te agrada planificar el itinerario detallado de tus vacaciones?", en: "Do you love organizing step-by-step vacation schedules for groups?", fr: "Adorez-vous planifier à la minute vos road-trips et voyages ?", ar: "هل تضع تخطيطاً دقيقاً لبرامج سفرك ورحلات الإجازة مع جميع الأصدقاء؟" },
  { id: 67, category: "hospitality", points: 5, es: "¿Te atrae la idea de trabajar en cruceros o agencias de viajes globales?", en: "Are you drawn to working aboard cruise ships or global travel firms?", fr: "Travailler pour des croisières ou des agences internationales de voyages ?", ar: "هل تدغدغ أحلامك رغبة العمل بالسفن السياحية البحرية أو شركات الطيران؟" },
  { id: 68, category: "hospitality", points: 5, es: "¿Te consideras una persona extrovertida que habla con desconocidos sin timidez?", en: "Are you an outgoing person who comfortably starts chats with strangers?", fr: "Êtes-vous sociable et dynamique avec des personnes inconnues ?", ar: "هل تصنف نفسك شخصاً اجتماعياً يحب بدء الحوارات مع الأجانب بودية؟" },
  { id: 69, category: "hospitality", points: 5, es: "¿Te agrada dar explicaciones orales y hablar en público con elocuencia?", en: "Do you feel confident speaking with eloquence in front of large crowds?", fr: "Parler de manière fluide, chaleureuse et claire en public ?", ar: "هل تعتقد أنك تملك حضوراً جميلاً وقدرة على الحديث ببيان أمام الجمهور؟" },
  { id: 70, category: "hospitality", points: 5, es: "¿Te interesan las diferencias culturales y las costumbres de cada país?", en: "Are you curious about global cultural variations and habits of nations?", fr: "Curieux d'en apprendre sur le folklore et les coutumes internationales ?", ar: "هل تسحرك عادات الشعوب واختلاف الملابس والمأكولات عبر بقاع الأرض؟" },
  { id: 71, category: "hospitality", points: 5, es: "¿Te gustaría estudiar los secretos de la gastronomía y vinos prestigiosos?", en: "Would you like to study fine food traditions, wines, and culinary trends?", fr: "Comprendre de près la haute gastronomie et le service de table ?", ar: "هل يثيرك عالم الفنون الفندقية وطبخ أطباق المطبخ الإسباني التقليدي؟" },
  { id: 72, category: "hospitality", points: 5, es: "¿Sueles dar indicaciones geográficas en la calle a turistas perdidos?", en: "Do you naturally help and guide lost tourists you spot in public?", fr: "Aidez-vous d'instinct les touristes égarés dans votre propre ville ?", ar: "هل تجد نفسك حريصاً على مساعدة وإرشاد السياح التائهين في شوارع مدينتك؟" },
  { id: 73, category: "hospitality", points: 5, es: "¿Te gustaría organizar grandes eventos de prensa, congresos o festivales?", en: "Would you like to coordinate major business seminars, congresses or shows?", fr: "Coordonner de grands congrès d’affaires, festivals de musique ?", ar: "هل ترغب في أن تكون منظماً للاجتماعات الدبلوماسية الدولية الكبرى؟" },
  { id: 74, category: "hospitality", points: 5, es: "¿Te atrae la idea de resolver problemas logísticos rápidos de reservas o vuelos?", en: "Would resolving airline tickets, re-routing, and hotel booking issues suit you?", fr: "Résoudre des problèmes immédiats d'annulations de vols d'hôtels ?", ar: "هل تريد العمل على إلغاء وحجز تذاكر الطيران للعملاء وحل الإشكاليات المستعجلة؟" },
  { id: 75, category: "hospitality", points: 5, es: "¿Prefieres un empleo dinámico moviéndote al aire libre a estar amarrado/a a un escritorio?", en: "Do you favor hands-on jobs involving outdoor work over desk routines?", fr: "Bouger dans les musées, monuments plutôt que fixer un écran fixe de bureau ?", ar: "هل تكره الجلوس الطويل المكتبي وتفضل عملاً حركياً تتجول فيه بالمدن؟" },
  { id: 76, category: "hospitality", points: 5, es: "¿Te ves enseñando tu lengua materna a extranjeros con paciencia y ritmo?", en: "Can you see yourself teaching native languages to expats patiently?", fr: "Transmettre vos langues avec pédagogie à des étudiants espagnols ?", ar: "هل يسعدك تدريس لغتك العربية أو الفرنسية لأشخاص إسبان يطلبونها؟" },
  { id: 77, category: "hospitality", points: 5, es: "¿Eres detallista sirviendo platos o decorando una mesa agradable?", en: "Are you attentive when serving courses or styling welcoming table setups?", fr: "Avoir le sens du détail pour dresser de magnifiques tables et dîners ?", ar: "هل تهتم بذوق تقديم ومظهر طاولة الطعام وطريقة استقبال الزوار؟" },
  { id: 78, category: "hospitality", points: 5, es: "¿Se te da bien aconsejar actividades divertidas y paseos de fin de semana?", en: "Do you naturally suggest enjoyable weekend activities or short trips?", fr: "Conseiller les meilleures randonnées et animations culturelles ?", ar: "هل أنت المرجع الأول لأصحابك في التخطيط لإجازة نهاية الأسبوع؟" },
  { id: 79, category: "hospitality", points: 5, es: "¿Te gustaría trabajar coordinando visitas a bodegas históricas y palacios?", en: "Would you like to manage excursions to historic palaces and vineyards?", fr: "Prendre en charge des tours de dégustation dans les châteaux ?", ar: "هل تهوى مرافقة الوفود لرؤية القصور الأندلسية والمعارض التاريخية؟" },
  { id: 80, category: "hospitality", points: 5, es: "¿Consideras que el buen humor y la hospitalidad son virtudes universales?", en: "Do you believe optimism and warm hospitality are the best social values?", fr: "Sourire, bien accueillir et réconforter les voyageurs ?”", ar: "هل تؤمن أن الابتسامة وحسن الاستقبال هما مفتاح النجاح لأي مهنة حية؟" },

  // SECTION 5: CREATIVE (81 - 100)
  { id: 81, category: "creative", points: 5, es: "¿Sueles fijarte en las combinaciones de colores de carteles o revistas?", en: "Are you drawn to color pairings, typography, and advertising graphics?", fr: "Remarquez-vous l'harmonie des polices d’écriture et couleurs ?", ar: "هل يشد انتباهك تناسق الألوان والخطوط المستخدمة في لافتات الشوارع؟" },
  { id: 82, category: "creative", points: 5, es: "¿Sientes la necesidad constante de dibujar, pintar o modelar digitalmente?", en: "Do you feel an urge to compile sketches, paint, or draft digital artworks?", fr: "Ressentez-vous le besoin de dessiner, peindre ou concevoir du visuel ?", ar: "هل تشعر برغبة فطرية بالرسم، كتابة الأفكار أو التعديل على الصور رقمياً؟" },
  { id: 83, category: "creative", points: 5, es: "¿Te gustaría dominar herramientas avanzadas de diseño como Photoshop o Figma?", en: "Do you want to master design and layout suites like Figma or Photoshop?", fr: "Voulez-vous manipuler Photoshop, Figma pour façonner du contenu ?", ar: "هل ترغب في التمكن والتميز في استخدام برامج التصميم فيجما وفوتوشوب؟" },
  { id: 84, category: "creative", points: 5, es: "¿Te interesa el diseño de interiores, arquitectura y distribución de espacios?", en: "Are you interested in interior design, physical spacing, and setup layouts?", fr: "L’architecture d’intérieur et l’aménagement d'espaces vous plaisent ?", ar: "هل تستهويك الديكورات المنزلية وهندسة الفضاءات وتوزيع الإضاءة؟" },
  { id: 85, category: "creative", points: 5, es: "¿Prefieres escribir poesías, guiones o crear historias ilustradas?", en: "Do you like writing novels, scripts, or illustrating custom cartoons?", fr: "Créer des bandes dessinées, scénariser des histoires ?", ar: "هل تحب كتابة نصوص إبداعية، قصص مصورة، أو تصميم مجلات ورقية؟" },
  { id: 86, category: "creative", points: 5, es: "¿Te entusiasma fotografiar paisajes, retratos y editar los tonos?", en: "Do you love taking photographs and balancing filters and colors?", fr: "Cadrer de belles photos, filmer et monter des vidéos ?", ar: "هل تشغلك صور الزوايا الفنية وتعديل درجات الألوان بالفلاتر والظلال؟" },
  { id: 87, category: "creative", points: 5, es: "¿Te fijas en si un producto tiene un envoltorio (packaging) hermoso?", en: "Do you check if product packaging has high-quality design value?", fr: "Prêtez-vous attention au packaging d'un parfum ou livre ?", ar: "هل تحكم على جودة وتأثير المنتج من روعة تصميم عبوته الخارجية؟" },
  { id: 88, category: "creative", points: 5, es: "¿Te gustaría rodar vídeos publicitarios y cortometrajes cinematográficos?", en: "Would you love recording video ads or creating small film stories?", fr: "Réaliser des clips, court-métrages ou monter des effets de son ?", ar: "هل تود التخطيط لكواليس تصوير ومونتاج لوحات إعلانية تلفزيونية؟" },
  { id: 89, category: "creative", points: 5, es: "¿Te atrae la moda, el estilismo de vestuario y las tendencias?", en: "Are you attracted to clothing, fashion design, styling, and outfits?", fr: "Attiré par l'univers de la mode, de la couture et du stylisme ?", ar: "هل تسترعي انتباهك خطوط الموضة، تصاميم الأزياء واختيار التنسيقات؟" },
  { id: 90, category: "creative", points: 5, es: "¿Prefieres la improvisación y originalidad libre frente a seguir reglas fijas?", en: "Do you favor absolute creative freedom over following manuals?", fr: "La liberté de création complète, la recherche de l'originalité ?", ar: "هل تحب الابتكار والتحليق خارج الصندوق بدلاً من التقيد الحرفي بالقواعد؟" },
  { id: 91, category: "creative", points: 5, es: "¿Te imaginas creando animaciones en 2D o 3D para cortos animados?", en: "Can you picture yourself compiling 2D/3D cartoon animations?", fr: "Aimeriez-vous créer des personnages et animer des dessins animés ?", ar: "هل يسعدك إنتاج أفلام كرتون أو واجهات متحركة ثنائية وثلاثية الأبعاد؟" },
  { id: 92, category: "creative", points: 5, es: "¿Te apasiona la música, mezclar sonido o tocar melodías?", en: "Are you passionate about composing music, audio tracks, or instruments?", fr: "La création musicale, jouer de la guitare ou moduler des sons ?", ar: "هل تشعر بشغف كبير بهندسة الموسيقى والتحكم بالتأثيرات البيئية الصوتية؟" },
  { id: 93, category: "creative", points: 5, es: "¿Sueles personalizar tus carpetas, apuntes o dispositivos con diseños?", en: "Do you style your notes, workspace, and phone layouts with custom themes?", fr: "Relier et embellir vos cahiers, posters de chambre ?", ar: "هل تصر على تزيين دفاتر مذكراتك ووضع ثيمات مميزة على واجهة هاتفك؟" },
  { id: 94, category: "creative", points: 5, es: "¿Te gusta experimentar con diferentes estilos tipográficos y fuentes?", en: "Do you like to experiment with different typographic styles and fonts?", fr: "Aimez-vous expérimenter différents styles de typographie et de police ?", ar: "هل تحب تجربة خطوط وأنماط كتابية إبداعية مختلفة لتجميل النصوص؟" },
  { id: 95, category: "creative", points: 5, es: "¿Te divierte modelar arcilla, esculpir, tallar o ensamblar obras manuales?", en: "Do you like pottery, wood carving, or assembling physical craft models?", fr: "Créer des sculptures de l’artisanat d'art, poterie ?", ar: "هل تجد راحة في الأعمال اليدوية والنحت والتشكيل المعماري البسيط؟" },
  { id: 96, category: "creative", points: 5, es: "¿Te interesa el diseño de una interfaz limpia de app (UI) para facilitar la lectura?", en: "Are you interested in clean mobile app layouts (UI) to help users read?", fr: "Créer des interfaces fluides d'applications (maquettes UX/UI) ?", ar: "هل يهمك تحسين جودة واجهات التطبيقات لتسهيل القراءة وتصفح المقالات؟" },
  { id: 97, category: "creative", points: 5, es: "¿Trabajas mejor con música sugerente y un cuaderno de bocetos abierto?", en: "Do you study best with ambient background music and a blank sketchpad?", fr: "Mieux réfléchir avec un crayon à la main et des musiques inspirantes ?", ar: "هل يعمل ذهنك بكفاءة فائقة حين تستمع لموسيقى هادئة وتمسك قلماً لتدوين أفكارك؟" },
  { id: 98, category: "creative", points: 5, es: "¿Te gustaría diseñar escaparates interactivos de grandes avenidas comerciales?", en: "Would designing interactive showcase storefronts for big retailers excite you?", fr: "Scénographier des vitrines de grands magasins de mode à Noël ?", ar: "هل تحب تصميم واجهات زجاجية تفاعلية للمتاجر الكبرى في شوارع مدريد؟" },
  { id: 99, category: "creative", points: 5, es: "¿Consideras que el arte es un medio vital para expresar tus sentimientos?", en: "Do you believe visual art is a crucial medium to express inner traits?", fr: "Pensez-vous que l'art est le meilleur vecteur d'émotions ?", ar: "هل تؤمن أن الفن التشكيلي والبصري هو وسيلتك الأمثل لمشاركة مشاعرك العميقة؟" },
  { id: 100, category: "creative", points: 5, es: "¿Te inspira el patrimonio de Gaudí, Picasso y los museos de España?", en: "Are you inspired by Gaudí architecture, Picasso, and Spanish museums?", fr: "Êtes-vous inspiré par l'extravagance de Gaudí et Dali en Espagne ?", ar: "هل يلهمك الفن المعماري لغودي واللوحات التشكيلية لبيكاسو في متاحف مدريد؟" }
];
